language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
# Do similar for other three images
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy
# Tagging
  - docker tag udagram-api-feed haunguyen489/udagram-api-feed:v1
# Do similar for other three images```
  - docker tag udagram-api-user haunguyen489/udagram-api-user:v1
  - docker tag udagram-frontend haunguyen489/udagram-frontend:v1
  - docker tag reverseproxy haunguyen489/reverseproxy:v1
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push haunguyen489/udagram-api-feed:v1
# Do similar for other three images
  - docker push haunguyen489/udagram-api-user:v1
  - docker push haunguyen489/udagram-frontend:v1
  - docker push haunguyen489/reverseproxy:v1